# Generated by Django 4.2.27 on 2026-01-21 20:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notification_type', models.CharField(choices=[('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ACCOUNT_UPDATE', 'Account Update'), ('SYSTEM_ALERT', 'System Alert'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], max_length=50, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=20, verbose_name='Channel')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Message')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Recipient Name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Recipient Phone')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Recipient Email')),
                ('sender_name', models.CharField(default='Super Legit Advance', max_length=100, verbose_name='Sender Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('delivery_attempts', models.IntegerField(default=0, verbose_name='Delivery Attempts')),
                ('delivery_error', models.TextField(blank=True, verbose_name='Delivery Error')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='External ID (Provider)')),
                ('related_object_type', models.CharField(blank=True, choices=[('LOAN', 'Loan'), ('CUSTOMER', 'Customer'), ('REPAYMENT', 'Repayment'), ('PAYMENT', 'Payment'), ('USER', 'User')], max_length=50, verbose_name='Related Object Type')),
                ('related_object_id', models.CharField(blank=True, max_length=50, verbose_name='Related Object ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost (KES)')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_id', models.CharField(blank=True, max_length=100, verbose_name='Message ID')),
                ('provider', models.CharField(choices=[('AFRICASTALKING', "Africa's Talking"), ('TWILIO', 'Twilio'), ('NEXMO', 'Nexmo'), ('INFOBIP', 'Infobip'), ('BULKSMS', 'BulkSMS'), ('OTHER', 'Other')], default='AFRICASTALKING', max_length=20, verbose_name='Provider')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('UNDELIVERED', 'Undelivered')], default='PENDING', max_length=20, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, verbose_name='Status Message')),
                ('units', models.IntegerField(default=1, verbose_name='Units Used')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost (KES)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('network_code', models.CharField(blank=True, max_length=20, verbose_name='Network Code')),
                ('network_name', models.CharField(blank=True, max_length=50, verbose_name='Network Name')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('SMS', 'SMS Template'), ('EMAIL', 'Email Template'), ('PUSH', 'Push Notification Template'), ('WHATSAPP', 'WhatsApp Template')], default='SMS', max_length=20, verbose_name='Template Type')),
                ('category', models.CharField(choices=[('LOAN', 'Loan Notifications'), ('PAYMENT', 'Payment Notifications'), ('ACCOUNT', 'Account Notifications'), ('MARKETING', 'Marketing'), ('ALERT', 'System Alerts'), ('OTHER', 'Other')], default='LOAN', max_length=20, verbose_name='Category')),
                ('language', models.CharField(choices=[('EN', 'English'), ('SW', 'Swahili')], default='EN', max_length=5, verbose_name='Language')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject (Email Only)')),
                ('content', models.TextField(help_text='Use {{variable}} for dynamic content', verbose_name='Template Content')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables used in the template', verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('character_limit', models.IntegerField(default=160, help_text='Maximum characters for SMS templates', verbose_name='Character Limit')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sample_data', models.JSONField(blank=True, default=dict, help_text='Sample data for testing the template', verbose_name='Sample Data')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name', 'category'],
            },
        ),
    ]
