# Generated by Django 4.2.27 on 2026-01-21 20:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Required. Must be a valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Required. Format: +254712345678', max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id_number', models.CharField(blank=True, db_index=True, help_text='National ID or Passport number', max_length=20, null=True, verbose_name='ID number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='gender')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True, verbose_name='marital status')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('loan_officer', 'Loan Officer'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('archived', 'Archived')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email and phone.', verbose_name='verified')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('kyc_completed', models.BooleanField(default=False, verbose_name='KYC completed')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='last login at')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='locked until')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA enabled')),
                ('two_factor_method', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('app', 'Authenticator App')], max_length=20, null=True, verbose_name='2FA method')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture (max 2MB)', null=True, upload_to='profiles/', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10, verbose_name='language')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='notifications enabled')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='marketing emails')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, verbose_name='last password change')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='privacy policy accepted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identification number.', max_length=50, unique=True, verbose_name='employee ID')),
                ('department', models.CharField(blank=True, help_text='Department within the organization.', max_length=100, verbose_name='department')),
                ('position', models.CharField(blank=True, help_text='Job title/position.', max_length=100, verbose_name='position')),
                ('hire_date', models.DateField(blank=True, help_text='Date when the staff member was hired.', null=True, verbose_name='hire date')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=50, verbose_name='employment type')),
                ('office_location', models.CharField(blank=True, help_text='Physical office location.', max_length=200, verbose_name='office location')),
                ('work_phone', models.CharField(blank=True, help_text='Work telephone number.', max_length=20, verbose_name='work phone')),
                ('work_email', models.EmailField(blank=True, help_text='Work email address (if different from personal).', max_length=254, verbose_name='work email')),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Overall performance rating (0-5).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='performance rating')),
                ('last_performance_review', models.DateField(blank=True, help_text='Date of last performance review.', null=True, verbose_name='last performance review')),
                ('can_approve_loans', models.BooleanField(default=False, help_text='Can this staff member approve loan applications?', verbose_name='can approve loans')),
                ('can_manage_customers', models.BooleanField(default=True, help_text='Can this staff member manage customer accounts?', verbose_name='can manage customers')),
                ('can_process_payments', models.BooleanField(default=True, help_text='Can this staff member process manual payments?', verbose_name='can process payments')),
                ('can_generate_reports', models.BooleanField(default=True, help_text='Can this staff member generate system reports?', verbose_name='can generate reports')),
                ('max_loan_approval_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loan amount this staff member can approve.', max_digits=12, null=True, verbose_name='max loan approval amount')),
                ('work_schedule', models.JSONField(default=dict, help_text='Weekly work schedule in JSON format.', verbose_name='work schedule')),
                ('is_available', models.BooleanField(default=True, help_text='Is the staff member currently available for work?', verbose_name='is available')),
                ('availability_note', models.TextField(blank=True, help_text='Notes about availability (e.g., vacation, sick leave).', verbose_name='availability note')),
                ('bank_name', models.CharField(blank=True, help_text='Name of bank for salary payments.', max_length=100, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for salary payments.', max_length=50, verbose_name='bank account number')),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch name.', max_length=100, verbose_name='bank branch')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person.', max_length=200, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact.', max_length=20, verbose_name='emergency contact phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship to emergency contact (e.g., spouse, parent).', max_length=50, verbose_name='emergency contact relationship')),
                ('id_document', models.FileField(blank=True, help_text='Copy of national ID or passport.', null=True, upload_to='staff/documents/id/', verbose_name='ID document')),
                ('employment_contract', models.FileField(blank=True, help_text='Signed employment contract.', null=True, upload_to='staff/documents/contracts/', verbose_name='employment contract')),
                ('other_documents', models.JSONField(default=list, help_text='List of other relevant documents.', verbose_name='other documents')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the staff member.', verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Direct supervisor/manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The user associated with this staff profile.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff profile',
                'verbose_name_plural': 'staff profiles',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['employee_id'], name='users_staff_employe_39d6d3_idx'), models.Index(fields=['department'], name='users_staff_departm_65b1ef_idx'), models.Index(fields=['position'], name='users_staff_positio_68b39e_idx'), models.Index(fields=['is_available'], name='users_staff_is_avai_304f65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='users_user_role_6e67fb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='users_user_is_acti_d093de_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('phone_number',), name='unique_phone'),
        ),
    ]
