# Generated by Django 4.2.27 on 2026-01-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='approval_tier',
            field=models.CharField(choices=[('junior', 'Junior Officer'), ('senior', 'Senior Officer'), ('manager', 'Manager'), ('director', 'Director')], default='junior', help_text='Approval authority level based on tier.', max_length=50, verbose_name='approval tier'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text="Custom permissions in JSON format, e.g., {'export_reports': true}", verbose_name='custom permissions'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='max_loan_approval_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loan amount this staff member can approve. None means unlimited.', max_digits=12, null=True, verbose_name='max loan approval amount'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='other_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of other relevant documents.', verbose_name='other documents'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='work_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly work schedule in JSON format.', verbose_name='work schedule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Incremented on failed login, reset on success.', verbose_name='failed login attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site. Synced with role.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_completed',
            field=models.BooleanField(default=False, help_text='Know Your Customer verification completed.', verbose_name='KYC completed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account is locked until this timestamp after too many failed attempts.', null=True, verbose_name='locked until'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('loan_officer', 'Loan Officer'), ('customer', 'Customer')], db_index=True, default='customer', help_text='User role determines access level and permissions.', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('archived', 'Archived')], db_index=True, default='active', help_text='Current status of the user account.', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['approval_tier'], name='users_staff_approva_261722_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['can_approve_loans'], name='users_staff_can_app_8ff161_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status', 'is_active'], name='users_user_role_1d3ed7_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('employee_id',), name='unique_employee_id'),
        ),
    ]
