# Generated by Django 4.2.27 on 2026-01-21 20:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('callback_type', models.CharField(choices=[('STK_PUSH', 'STK Push Callback'), ('C2B_VALIDATION', 'C2B Validation'), ('C2B_CONFIRMATION', 'C2B Confirmation'), ('B2C_RESULT', 'B2C Result'), ('B2C_TIMEOUT', 'B2C Timeout'), ('REVERSAL_RESULT', 'Reversal Result')], max_length=30, verbose_name='Callback Type')),
                ('callback_data', models.JSONField(default=dict, verbose_name='Callback Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('headers', models.JSONField(default=dict, verbose_name='Request Headers')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('processing_notes', models.TextField(blank=True, verbose_name='Processing Notes')),
                ('has_error', models.BooleanField(default=False, verbose_name='Has Error')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'M-Pesa Callback',
                'verbose_name_plural': 'M-Pesa Callbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_reference', models.CharField(max_length=50, unique=True, verbose_name='Payment Reference')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount (KES)')),
                ('description', models.TextField(blank=True, verbose_name='Payment Description')),
                ('payment_type', models.CharField(choices=[('LOAN_REPAYMENT', 'Loan Repayment'), ('LOAN_APPLICATION_FEE', 'Loan Application Fee'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('OTHER', 'Other')], default='LOAN_REPAYMENT', max_length=30, verbose_name='Payment Type')),
                ('transaction_type', models.CharField(choices=[('CUSTOMER_PAY_BILL_ONLINE', 'Customer Pay Bill Online'), ('CUSTOMER_BUY_GOODS_ONLINE', 'Customer Buy Goods Online')], default='CUSTOMER_PAY_BILL_ONLINE', max_length=50, verbose_name='Transaction Type')),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Merchant Request ID')),
                ('checkout_request_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Checkout Request ID')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='Result Code')),
                ('result_description', models.TextField(blank=True, verbose_name='Result Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Initiated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('callback_metadata', models.JSONField(blank=True, default=dict, verbose_name='Callback Metadata')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Retry At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'M-Pesa Payment',
                'verbose_name_plural': 'M-Pesa Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('mpesa_receipt_number', models.CharField(max_length=50, unique=True, verbose_name='M-Pesa Receipt Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount (KES)')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REVERSAL', 'Reversal'), ('REFUND', 'Refund')], default='PAYMENT', max_length=20, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20, verbose_name='Transaction Status')),
                ('conversation_id', models.CharField(blank=True, max_length=100, verbose_name='Conversation ID')),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, verbose_name='Originator Conversation ID')),
                ('account_reference', models.CharField(blank=True, max_length=100, verbose_name='Account Reference')),
                ('transaction_description', models.TextField(blank=True, verbose_name='Transaction Description')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance (KES)')),
                ('original_transaction_id', models.CharField(blank=True, max_length=50, verbose_name='Original Transaction ID')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='Reversal Reason')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reversed At')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Raw Response')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
