# Generated by Django 4.2.27 on 2026-01-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repayments', '0001_initial'),
        ('customers', '0002_initial'),
        ('loans', '0002_initial'),
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='mpesa.mpesapayment', verbose_name='M-Pesa Payment'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='loans.loan', verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='repayments.repayment', verbose_name='Repayment'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesacallback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpesacallback',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='mpesa.mpesapayment', verbose_name='M-Pesa Payment'),
        ),
        migrations.AddField(
            model_name='mpesacallback',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='mpesa_mpesa_mpesa_r_63a7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_id'], name='mpesa_mpesa_transac_bfb356_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status'], name='mpesa_mpesa_status_b7937d_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_date'], name='mpesa_mpesa_transac_225cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number'], name='mpesa_mpesa_phone_n_1a4883_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['payment_reference'], name='mpesa_mpesa_payment_3f41c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['merchant_request_id'], name='mpesa_mpesa_merchan_ee9987_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_mpesa_checkou_38cbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status'], name='mpesa_mpesa_status_dafcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['customer', 'status'], name='mpesa_mpesa_custome_300ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['initiated_at'], name='mpesa_mpesa_initiat_c1e3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['callback_type'], name='mpesa_mpesa_callbac_fa2ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['is_processed'], name='mpesa_mpesa_is_proc_ecf836_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['has_error'], name='mpesa_mpesa_has_err_203b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesacallback',
            index=models.Index(fields=['created_at'], name='mpesa_mpesa_created_5a35be_idx'),
        ),
    ]
