# Generated by Django 4.2.27 on 2026-01-21 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Audit Log ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VERIFY', 'Verify'), ('BLACKLIST', 'Blacklist'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('NOTIFICATION', 'Notification'), ('REPORT', 'Report'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('SECURITY', 'Security Event'), ('SYSTEM', 'System Event'), ('OTHER', 'Other')], max_length=50, verbose_name='Action')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20, verbose_name='Severity Level')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=20, verbose_name='Status')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Object ID')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes Made')),
                ('previous_state', models.JSONField(blank=True, null=True, verbose_name='Previous State')),
                ('new_state', models.JSONField(blank=True, null=True, verbose_name='New State')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP Method')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('request_params', models.JSONField(blank=True, null=True, verbose_name='Request Parameters')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='Response Status Code')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('error_traceback', models.TextField(blank=True, verbose_name='Error Traceback')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Module/App')),
                ('feature', models.CharField(blank=True, max_length=100, verbose_name='Feature')),
                ('tags', models.JSONField(blank=True, default=list, null=True, verbose_name='Tags')),
                ('compliance_id', models.CharField(blank=True, max_length=100, verbose_name='Compliance ID')),
                ('is_compliance_event', models.BooleanField(default=False, verbose_name='Compliance Event')),
                ('retention_days', models.IntegerField(default=365, verbose_name='Retention Period (days)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archive_date', models.DateTimeField(blank=True, null=True, verbose_name='Archive Date')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
