# Generated by Django 4.2.27 on 2026-01-26 03:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Income (KES)'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='other_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Other Monthly Income (KES)'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='total_monthly_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Monthly Expenses (KES)'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'completion_date'], name='loans_loan_status_5748df_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['reviewer', 'status'], name='loans_loana_reviewe_c5e4fe_idx'),
        ),
    ]
