# NEW FILE - Customer-specific constants

# Customer statuses
CUSTOMER_STATUS_ACTIVE = 'ACTIVE'
CUSTOMER_STATUS_INACTIVE = 'INACTIVE'
CUSTOMER_STATUS_BLACKLISTED = 'BLACKLISTED'
CUSTOMER_STATUS_DECEASED = 'DECEASED'

CUSTOMER_STATUS_CHOICES = [
    (CUSTOMER_STATUS_ACTIVE, 'Active'),
    (CUSTOMER_STATUS_INACTIVE, 'Inactive'),
    (CUSTOMER_STATUS_BLACKLISTED, 'Blacklisted'),
    (CUSTOMER_STATUS_DECEASED, 'Deceased'),
]

# Risk levels
RISK_LEVEL_LOW = 'LOW'
RISK_LEVEL_MEDIUM = 'MEDIUM'
RISK_LEVEL_HIGH = 'HIGH'

RISK_LEVEL_CHOICES = [
    (RISK_LEVEL_LOW, 'Low Risk'),
    (RISK_LEVEL_MEDIUM, 'Medium Risk'),
    (RISK_LEVEL_HIGH, 'High Risk'),
]

# Employment types
EMPLOYMENT_EMPLOYED = 'EMPLOYED'
EMPLOYMENT_SELF_EMPLOYED = 'SELF_EMPLOYED'
EMPLOYMENT_UNEMPLOYED = 'UNEMPLOYED'
EMPLOYMENT_STUDENT = 'STUDENT'
EMPLOYMENT_RETIRED = 'RETIRED'

EMPLOYMENT_TYPE_CHOICES = [
    (EMPLOYMENT_EMPLOYED, 'Employed'),
    (EMPLOYMENT_SELF_EMPLOYED, 'Self-Employed'),
    (EMPLOYMENT_UNEMPLOYED, 'Unemployed'),
    (EMPLOYMENT_STUDENT, 'Student'),
    (EMPLOYMENT_RETIRED, 'Retired'),
]

# File upload limits
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_DOCUMENT_EXTENSIONS = ['pdf', 'jpg', 'jpeg', 'png']
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png']

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# KYC/Verification
KYC_VERIFIED = 'VERIFIED'
KYC_PENDING = 'PENDING'
KYC_REJECTED = 'REJECTED'

KYC_STATUS_CHOICES = [
    (KYC_VERIFIED, 'Verified'),
    (KYC_PENDING, 'Pending'),
    (KYC_REJECTED, 'Rejected'),
]