# Generated by Django 4.2.27 on 2026-01-26 01:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, editable=False, help_text='Automatically calculated from date_of_birth', null=True, verbose_name='Age (Calculated)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Customer Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.FileField(blank=True, help_text='PDF, JPG, or PNG (Max 5MB)', null=True, upload_to='identity_docs/%Y/%m/%d/', verbose_name='ID Document'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_photo',
            field=models.ImageField(blank=True, help_text='JPG or PNG (Max 3MB)', null=True, upload_to='customer_photos/%Y/%m/%d/', verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +254XXXXXXXXX', regex='^\\+254\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLISTED', 'Blacklisted'), ('DECEASED', 'Deceased')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone must be in format: +254XXXXXXXXX', regex='^\\+254\\d{9}$')], verbose_name='Employer Phone'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='years_of_service',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Years of Service'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at', 'status'], name='customers_c_created_56c225_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['county', 'status'], name='customers_c_county_e6cdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['date_of_birth'], name='customers_c_date_of_59c920_idx'),
        ),
    ]
