# backend/apps/reports/generators/excel_generator.py
import io
import pandas as pd
from datetime import datetime
from django.utils import timezone
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Border, Side, Alignment,
    NamedStyle, numbers
)
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image
from openpyxl.chart import (
    BarChart, LineChart, PieChart, Reference,
    Series
)
import matplotlib.pyplot as plt
import seaborn as sns


class ExcelGenerator:
    """
    Excel report generator for Super Legit Advance.
    """
    
    def __init__(self):
        """Initialize Excel generator."""
        self.workbook = None
        self.default_styles = {}
    
    def generate_report(self, report_name, report_data):
        """
        Generate an Excel report from report data.
        
        Args:
            report_name (str): Name of the report
            report_data (dict): Report data dictionary
            
        Returns:
            bytes: Excel file content
        """
        # Create workbook
        self.workbook = Workbook()
        self._define_styles()
        
        # Remove default sheet
        default_sheet = self.workbook.active
        self.workbook.remove(default_sheet)
        
        # Create summary sheet
        summary_sheet = self.workbook.create_sheet(title="Summary")
        self._create_summary_sheet(summary_sheet, report_name, report_data)
        
        # Create data sheets based on report type
        if 'loans' in report_name.lower():
            self._create_loans_sheets(report_data)
        elif 'payments' in report_name.lower():
            self._create_payments_sheets(report_data)
        elif 'customers' in report_name.lower():
            self._create_customers_sheets(report_data)
        elif 'performance' in report_name.lower():
            self._create_performance_sheets(report_data)
        
        # Add metadata sheet
        self._create_metadata_sheet(report_data.get('metadata', {}))
        
        # Save to bytes
        output = io.BytesIO()
        self.workbook.save(output)
        output.seek(0)
        
        excel_content = output.getvalue()
        output.close()
        
        return excel_content
    
    def generate_export(self, title, columns, data, generated_by=None):
        """
        Generate an Excel export of data.
        
        Args:
            title (str): Export title
            columns (list): Column names
            data (list): List of data rows
            generated_by (str): Name of user who generated the export
            
        Returns:
            bytes: Excel file content
        """
        # Create workbook
        self.workbook = Workbook()
        self._define_styles()
        
        # Create main sheet
        sheet = self.workbook.active
        sheet.title = "Data"
        
        # Add header
        sheet.append([title])
        sheet.merge_cells('A1:{}1'.format(get_column_letter(len(columns))))
        sheet['A1'].style = 'Title'
        
        # Add metadata
        if generated_by:
            sheet.append(['Generated by:', generated_by])
        sheet.append(['Generated on:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')])
        sheet.append(['Total records:', len(data)])
        sheet.append([])  # Empty row
        
        # Add column headers
        sheet.append(columns)
        header_row = sheet.max_row
        
        # Apply header style
        for col in range(1, len(columns) + 1):
            cell = sheet.cell(row=header_row, column=col)
            cell.style = 'Header'
        
        # Add data
        for row in data:
            sheet.append(row)
        
        # Auto-adjust column widths
        self._auto_adjust_columns(sheet)
        
        # Add summary sheet
        summary_sheet = self.workbook.create_sheet(title="Summary")
        self._create_export_summary(summary_sheet, title, columns, data, generated_by)
        
        # Save to bytes
        output = io.BytesIO()
        self.workbook.save(output)
        output.seek(0)
        
        excel_content = output.getvalue()
        output.close()
        
        return excel_content
    
    def _define_styles(self):
        """Define cell styles for the workbook."""
        # Title style
        title_style = NamedStyle(name="Title")
        title_style.font = Font(name='Arial', size=16, bold=True, color='2C3E50')
        title_style.alignment = Alignment(horizontal='center', vertical='center')
        self.workbook.add_named_style(title_style)
        
        # Header style
        header_style = NamedStyle(name="Header")
        header_style.font = Font(name='Arial', size=11, bold=True, color='FFFFFF')
        header_style.fill = PatternFill(start_color='2C3E50', end_color='2C3E50', fill_type='solid')
        header_style.border = Border(
            left=Side(border_style='thin', color='000000'),
            right=Side(border_style='thin', color='000000'),
            top=Side(border_style='thin', color='000000'),
            bottom=Side(border_style='thin', color='000000')
        )
        header_style.alignment = Alignment(horizontal='center', vertical='center')
        self.workbook.add_named_style(header_style)
        
        # Subheader style
        subheader_style = NamedStyle(name="Subheader")
        subheader_style.font = Font(name='Arial', size=12, bold=True, color='34495E')
        subheader_style.alignment = Alignment(horizontal='left', vertical='center')
        self.workbook.add_named_style(subheader_style)
        
        # Normal style
        normal_style = NamedStyle(name="Normal")
        normal_style.font = Font(name='Arial', size=10, color='000000')
        normal_style.alignment = Alignment(vertical='center')
        self.workbook.add_named_style(normal_style)
        
        # Amount style
        amount_style = NamedStyle(name="Amount")
        amount_style.font = Font(name='Courier New', size=10, color='000000')
        amount_style.number_format = numbers.FORMAT_NUMBER_COMMA_SEPARATED1
        amount_style.alignment = Alignment(horizontal='right', vertical='center')
        self.workbook.add_named_style(amount_style)
        
        # Percentage style
        percent_style = NamedStyle(name="Percentage")
        percent_style.font = Font(name='Arial', size=10, color='000000')
        percent_style.number_format = '0.00%'
        percent_style.alignment = Alignment(horizontal='right', vertical='center')
        self.workbook.add_named_style(percent_style)
        
        # Date style
        date_style = NamedStyle(name="Date")
        date_style.font = Font(name='Arial', size=10, color='000000')
        date_style.number_format = 'YYYY-MM-DD'
        date_style.alignment = Alignment(horizontal='center', vertical='center')
        self.workbook.add_named_style(date_style)
        
        # Highlight style
        highlight_style = NamedStyle(name="Highlight")
        highlight_style.font = Font(name='Arial', size=10, bold=True, color='000000')
        highlight_style.fill = PatternFill(start_color='FFF3CD', end_color='FFF3CD', fill_type='solid')
        highlight_style.border = Border(
            left=Side(border_style='thin', color='FFC107'),
            right=Side(border_style='thin', color='FFC107'),
            top=Side(border_style='thin', color='FFC107'),
            bottom=Side(border_style='thin', color='FFC107')
        )
        self.workbook.add_named_style(highlight_style)
        
        # Total style
        total_style = NamedStyle(name="Total")
        total_style.font = Font(name='Arial', size=10, bold=True, color='FFFFFF')
        total_style.fill = PatternFill(start_color='2C3E50', end_color='2C3E50', fill_type='solid')
        total_style.border = Border(
            left=Side(border_style='thin', color='000000'),
            right=Side(border_style='thin', color='000000'),
            top=Side(border_style='thin', color='000000'),
            bottom=Side(border_style='thin', color='000000')
        )
        total_style.alignment = Alignment(horizontal='right', vertical='center')
        self.workbook.add_named_style(total_style)
        
        # Store style names
        self.default_styles = {
            'title': 'Title',
            'header': 'Header',
            'subheader': 'Subheader',
            'normal': 'Normal',
            'amount': 'Amount',
            'percentage': 'Percentage',
            'date': 'Date',
            'highlight': 'Highlight',
            'total': 'Total',
        }
    
    def _create_summary_sheet(self, sheet, report_name, report_data):
        """Create summary sheet for report."""
        # Title
        sheet.append([report_name])
        sheet.merge_cells('A1:E1')
        sheet['A1'].style = self.default_styles['title']
        
        # Metadata
        metadata = report_data.get('metadata', {})
        sheet.append(['Generated by:', metadata.get('generated_by', 'System')])
        sheet.append(['Generated at:', metadata.get('generated_at', timezone.now().strftime('%Y-%m-%d %H:%M:%S'))])
        sheet.append(['Report type:', metadata.get('report_type', 'General')])
        
        if 'period' in report_data:
            sheet.append(['Period:', report_data['period']])
        
        sheet.append([])  # Empty row
        
        # Summary section
        summary = report_data.get('summary', {})
        if summary:
            sheet.append(['SUMMARY'])
            sheet.merge_cells('A7:E7')
            sheet['A7'].style = self.default_styles['subheader']
            
            row = 8
            for key, value in summary.items():
                display_key = ' '.join(word.capitalize() for word in key.split('_'))
                
                if isinstance(value, (int, float)):
                    if 'amount' in key.lower() or 'total' in key.lower() or 'balance' in key.lower():
                        sheet.cell(row=row, column=1, value=display_key).style = self.default_styles['normal']
                        sheet.cell(row=row, column=2, value=float(value)).style = self.default_styles['amount']
                    elif 'rate' in key.lower() or 'percentage' in key.lower():
                        sheet.cell(row=row, column=1, value=display_key).style = self.default_styles['normal']
                        sheet.cell(row=row, column=2, value=float(value) / 100).style = self.default_styles['percentage']
                    else:
                        sheet.cell(row=row, column=1, value=display_key).style = self.default_styles['normal']
                        sheet.cell(row=row, column=2, value=value).style = self.default_styles['normal']
                else:
                    sheet.cell(row=row, column=1, value=display_key).style = self.default_styles['normal']
                    sheet.cell(row=row, column=2, value=str(value)).style = self.default_styles['normal']
                
                row += 1
        
        # Auto-adjust columns
        self._auto_adjust_columns(sheet)
    
    def _create_loans_sheets(self, report_data):
        """Create loans data sheets."""
        # Loans detail sheet
        loans_sheet = self.workbook.create_sheet(title="Loans Detail")
        
        # Header
        loans_sheet.append(['LOANS DETAIL'])
        loans_sheet.merge_cells('A1:G1')
        loans_sheet['A1'].style = self.default_styles['title']
        
        # Column headers
        headers = [
            'Loan Number', 'Customer Name', 'Product',
            'Amount Approved', 'Amount Disbursed', 'Outstanding Balance',
            'Status', 'Disbursement Date'
        ]
        loans_sheet.append(headers)
        
        # Apply header style
        header_row = loans_sheet.max_row
        for col in range(1, len(headers) + 1):
            loans_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
        
        # Data
        loans = report_data.get('loans', [])
        for loan in loans:
            row = [
                loan.get('loan_number', ''),
                f"{loan.get('customer__first_name', '')} {loan.get('customer__last_name', '')}",
                loan.get('loan_product__name', 'N/A'),
                float(loan.get('amount_approved', 0)),
                float(loan.get('amount_disbursed', 0)),
                float(loan.get('outstanding_balance', 0)),
                loan.get('status', ''),
                loan.get('disbursement_date', '')[:10] if loan.get('disbursement_date') else ''
            ]
            loans_sheet.append(row)
        
        # Apply styles to data rows
        for row in range(header_row + 1, loans_sheet.max_row + 1):
            # Amount columns
            for col in [4, 5, 6]:  # D, E, F columns
                loans_sheet.cell(row=row, column=col).style = self.default_styles['amount']
            
            # Date column
            loans_sheet.cell(row=row, column=8).style = self.default_styles['date']
            
            # Other columns
            for col in [1, 2, 3, 7]:
                loans_sheet.cell(row=row, column=col).style = self.default_styles['normal']
        
        # Add totals row
        if loans:
            total_row = loans_sheet.max_row + 1
            loans_sheet.cell(row=total_row, column=1, value='TOTAL').style = self.default_styles['total']
            
            # Sum amounts
            for col, col_letter in enumerate([4, 5, 6], start=4):  # D, E, F columns
                start_cell = f"{col_letter}{header_row + 1}"
                end_cell = f"{col_letter}{total_row - 1}"
                formula = f"=SUM({start_cell}:{end_cell})"
                loans_sheet.cell(row=total_row, column=col, value=formula).style = self.default_styles['total']
        
        # Auto-adjust columns
        self._auto_adjust_columns(loans_sheet)
        
        # Distribution sheets
        self._create_distribution_sheets(report_data)
    
    def _create_payments_sheets(self, report_data):
        """Create payments data sheets."""
        # Payments detail sheet
        payments_sheet = self.workbook.create_sheet(title="Payments Detail")
        
        # Header
        payments_sheet.append(['PAYMENTS DETAIL'])
        payments_sheet.merge_cells('A1:H1')
        payments_sheet['A1'].style = self.default_styles['title']
        
        # Column headers
        headers = [
            'Payment Reference', 'Loan Number', 'Customer Name',
            'Amount', 'Payment Method', 'Status',
            'Payment Date', 'Created Date'
        ]
        payments_sheet.append(headers)
        
        # Apply header style
        header_row = payments_sheet.max_row
        for col in range(1, len(headers) + 1):
            payments_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
        
        # Data
        payments = report_data.get('payments', [])
        for payment in payments:
            row = [
                payment.get('payment_reference', ''),
                payment.get('loan__loan_number', 'N/A'),
                f"{payment.get('loan__customer__first_name', '')} {payment.get('loan__customer__last_name', '')}",
                float(payment.get('amount', 0)),
                payment.get('payment_method', ''),
                payment.get('status', ''),
                payment.get('payment_date', '')[:10] if payment.get('payment_date') else '',
                payment.get('created_at', '')[:10] if payment.get('created_at') else ''
            ]
            payments_sheet.append(row)
        
        # Apply styles to data rows
        for row in range(header_row + 1, payments_sheet.max_row + 1):
            # Amount column
            payments_sheet.cell(row=row, column=4).style = self.default_styles['amount']
            
            # Date columns
            for col in [7, 8]:  # G, H columns
                payments_sheet.cell(row=row, column=col).style = self.default_styles['date']
            
            # Other columns
            for col in [1, 2, 3, 5, 6]:
                payments_sheet.cell(row=row, column=col).style = self.default_styles['normal']
        
        # Add totals row
        if payments:
            total_row = payments_sheet.max_row + 1
            payments_sheet.cell(row=total_row, column=1, value='TOTAL').style = self.default_styles['total']
            
            # Sum amounts
            start_cell = f"D{header_row + 1}"
            end_cell = f"D{total_row - 1}"
            formula = f"=SUM({start_cell}:{end_cell})"
            payments_sheet.cell(row=total_row, column=4, value=formula).style = self.default_styles['total']
        
        # Auto-adjust columns
        self._auto_adjust_columns(payments_sheet)
        
        # Method distribution sheet
        self._create_payment_method_sheet(report_data)
    
    def _create_customers_sheets(self, report_data):
        """Create customers data sheets."""
        # Customers detail sheet
        customers_sheet = self.workbook.create_sheet(title="Customers Detail")
        
        # Header
        customers_sheet.append(['CUSTOMERS DETAIL'])
        customers_sheet.merge_cells('A1:J1')
        customers_sheet['A1'].style = self.default_styles['title']
        
        # Column headers
        headers = [
            'Customer Number', 'First Name', 'Last Name',
            'Phone Number', 'Email', 'ID Number',
            'County', 'Status', 'Risk Level', 'Credit Score'
        ]
        customers_sheet.append(headers)
        
        # Apply header style
        header_row = customers_sheet.max_row
        for col in range(1, len(headers) + 1):
            customers_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
        
        # Data
        customers = report_data.get('customers', [])
        for customer in customers:
            row = [
                customer.get('customer_number', ''),
                customer.get('first_name', ''),
                customer.get('last_name', ''),
                customer.get('phone_number', ''),
                customer.get('email', ''),
                customer.get('id_number', ''),
                customer.get('county', ''),
                customer.get('status', ''),
                customer.get('risk_level', ''),
                float(customer.get('credit_score', 0))
            ]
            customers_sheet.append(row)
        
        # Apply styles to data rows
        for row in range(header_row + 1, customers_sheet.max_row + 1):
            # Credit score column
            customers_sheet.cell(row=row, column=10).style = self.default_styles['amount']
            
            # Other columns
            for col in range(1, 10):
                customers_sheet.cell(row=row, column=col).style = self.default_styles['normal']
        
        # Auto-adjust columns
        self._auto_adjust_columns(customers_sheet)
        
        # Demographics sheets
        self._create_demographics_sheets(report_data)
    
    def _create_performance_sheets(self, report_data):
        """Create performance metrics sheets."""
        # KPIs sheet
        kpis_sheet = self.workbook.create_sheet(title="KPIs")
        
        # Header
        kpis_sheet.append(['KEY PERFORMANCE INDICATORS'])
        kpis_sheet.merge_cells('A1:B1')
        kpis_sheet['A1'].style = self.default_styles['title']
        
        # KPI data
        kpis = report_data.get('key_performance_indicators', {})
        row = 3
        
        for kpi_name, kpi_value in kpis.items():
            display_name = ' '.join(word.capitalize() for word in kpi_name.split('_'))
            
            if isinstance(kpi_value, dict):
                # Nested KPIs
                kpis_sheet.cell(row=row, column=1, value=display_name).style = self.default_styles['subheader']
                row += 1
                
                for sub_name, sub_value in kpi_value.items():
                    sub_display = ' '.join(word.capitalize() for word in sub_name.split('_'))
                    kpis_sheet.cell(row=row, column=1, value=f"  {sub_display}").style = self.default_styles['normal']
                    
                    if isinstance(sub_value, (int, float)):
                        if 'rate' in sub_name or 'percentage' in sub_name:
                            kpis_sheet.cell(row=row, column=2, value=float(sub_value) / 100).style = self.default_styles['percentage']
                        else:
                            kpis_sheet.cell(row=row, column=2, value=float(sub_value)).style = self.default_styles['amount']
                    else:
                        kpis_sheet.cell(row=row, column=2, value=str(sub_value)).style = self.default_styles['normal']
                    
                    row += 1
            else:
                kpis_sheet.cell(row=row, column=1, value=display_name).style = self.default_styles['normal']
                
                if isinstance(kpi_value, (int, float)):
                    if 'rate' in kpi_name or 'percentage' in kpi_name:
                        kpis_sheet.cell(row=row, column=2, value=float(kpi_value) / 100).style = self.default_styles['percentage']
                    else:
                        kpis_sheet.cell(row=row, column=2, value=float(kpi_value)).style = self.default_styles['amount']
                else:
                    kpis_sheet.cell(row=row, column=2, value=str(kpi_value)).style = self.default_styles['normal']
                
                row += 1
        
        # Auto-adjust columns
        self._auto_adjust_columns(kpis_sheet)
        
        # Trends sheet
        self._create_trends_sheet(report_data)
        
        # Metrics sheets
        self._create_metrics_sheets(report_data)
    
    def _create_distribution_sheets(self, report_data):
        """Create distribution analysis sheets for loans."""
        # Status distribution
        status_data = report_data.get('status_distribution', [])
        if status_data:
            status_sheet = self.workbook.create_sheet(title="Status Distribution")
            
            status_sheet.append(['LOAN STATUS DISTRIBUTION'])
            status_sheet.merge_cells('A1:D1')
            status_sheet['A1'].style = self.default_styles['title']
            
            # Headers
            status_sheet.append(['Status', 'Count', 'Amount', 'Percentage'])
            header_row = status_sheet.max_row
            for col in range(1, 5):
                status_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
            
            # Data
            total_count = sum(item.get('count', 0) for item in status_data)
            total_amount = sum(item.get('amount', 0) for item in status_data)
            
            for item in status_data:
                count = item.get('count', 0)
                amount = item.get('amount', 0)
                percentage = (count / total_count * 100) if total_count > 0 else 0
                
                status_sheet.append([
                    item.get('status', ''),
                    count,
                    float(amount),
                    percentage / 100  # Convert to decimal for percentage format
                ])
            
            # Apply styles
            for row in range(header_row + 1, status_sheet.max_row + 1):
                status_sheet.cell(row=row, column=1).style = self.default_styles['normal']
                status_sheet.cell(row=row, column=2).style = self.default_styles['normal']
                status_sheet.cell(row=row, column=3).style = self.default_styles['amount']
                status_sheet.cell(row=row, column=4).style = self.default_styles['percentage']
            
            # Totals
            total_row = status_sheet.max_row + 1
            status_sheet.cell(row=total_row, column=1, value='TOTAL').style = self.default_styles['total']
            status_sheet.cell(row=total_row, column=2, value=total_count).style = self.default_styles['total']
            status_sheet.cell(row=total_row, column=3, value=float(total_amount)).style = self.default_styles['total']
            status_sheet.cell(row=total_row, column=4, value=1).style = self.default_styles['total']  # 100%
            
            # Auto-adjust columns
            self._auto_adjust_columns(status_sheet)
            
            # Create chart
            self._create_pie_chart(status_sheet, 'Status Distribution', 'A', 'B', header_row + 1, status_sheet.max_row - 1)
    
    def _create_payment_method_sheet(self, report_data):
        """Create payment method distribution sheet."""
        method_data = report_data.get('method_distribution', [])
        if method_data:
            method_sheet = self.workbook.create_sheet(title="Payment Methods")
            
            method_sheet.append(['PAYMENT METHOD DISTRIBUTION'])
            method_sheet.merge_cells('A1:D1')
            method_sheet['A1'].style = self.default_styles['title']
            
            # Headers
            method_sheet.append(['Method', 'Count', 'Amount', 'Percentage'])
            header_row = method_sheet.max_row
            for col in range(1, 5):
                method_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
            
            # Data
            total_count = sum(item.get('count', 0) for item in method_data)
            total_amount = sum(item.get('amount', 0) for item in method_data)
            
            for item in method_data:
                count = item.get('count', 0)
                amount = item.get('amount', 0)
                percentage = (count / total_count * 100) if total_count > 0 else 0
                
                method_sheet.append([
                    item.get('payment_method', ''),
                    count,
                    float(amount),
                    percentage / 100
                ])
            
            # Apply styles
            for row in range(header_row + 1, method_sheet.max_row + 1):
                method_sheet.cell(row=row, column=1).style = self.default_styles['normal']
                method_sheet.cell(row=row, column=2).style = self.default_styles['normal']
                method_sheet.cell(row=row, column=3).style = self.default_styles['amount']
                method_sheet.cell(row=row, column=4).style = self.default_styles['percentage']
            
            # Totals
            total_row = method_sheet.max_row + 1
            method_sheet.cell(row=total_row, column=1, value='TOTAL').style = self.default_styles['total']
            method_sheet.cell(row=total_row, column=2, value=total_count).style = self.default_styles['total']
            method_sheet.cell(row=total_row, column=3, value=float(total_amount)).style = self.default_styles['total']
            method_sheet.cell(row=total_row, column=4, value=1).style = self.default_styles['total']
            
            # Auto-adjust columns
            self._auto_adjust_columns(method_sheet)
            
            # Create chart
            self._create_bar_chart(method_sheet, 'Payment Methods', 'A', 'C', header_row + 1, method_sheet.max_row - 1)
    
    def _create_demographics_sheets(self, report_data):
        """Create demographics analysis sheets."""
        demographics = report_data.get('demographics', {})
        
        # Gender distribution
        gender_data = demographics.get('gender_distribution', [])
        if gender_data:
            gender_sheet = self.workbook.create_sheet(title="Gender Distribution")
            
            gender_sheet.append(['GENDER DISTRIBUTION'])
            gender_sheet.merge_cells('A1:C1')
            gender_sheet['A1'].style = self.default_styles['title']
            
            # Headers
            gender_sheet.append(['Gender', 'Count', 'Percentage'])
            header_row = gender_sheet.max_row
            for col in range(1, 4):
                gender_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
            
            # Data
            total_count = sum(item.get('count', 0) for item in gender_data)
            
            for item in gender_data:
                count = item.get('count', 0)
                gender = item.get('gender', '')
                display_gender = 'Male' if gender == 'M' else 'Female' if gender == 'F' else 'Other'
                percentage = (count / total_count * 100) if total_count > 0 else 0
                
                gender_sheet.append([
                    display_gender,
                    count,
                    percentage / 100
                ])
            
            # Apply styles
            for row in range(header_row + 1, gender_sheet.max_row + 1):
                gender_sheet.cell(row=row, column=1).style = self.default_styles['normal']
                gender_sheet.cell(row=row, column=2).style = self.default_styles['normal']
                gender_sheet.cell(row=row, column=3).style = self.default_styles['percentage']
            
            # Totals
            total_row = gender_sheet.max_row + 1
            gender_sheet.cell(row=total_row, column=1, value='TOTAL').style = self.default_styles['total']
            gender_sheet.cell(row=total_row, column=2, value=total_count).style = self.default_styles['total']
            gender_sheet.cell(row=total_row, column=3, value=1).style = self.default_styles['total']
            
            # Auto-adjust columns
            self._auto_adjust_columns(gender_sheet)
    
    def _create_trends_sheet(self, report_data):
        """Create trends analysis sheet."""
        trends = report_data.get('trends', {})
        
        if trends:
            trends_sheet = self.workbook.create_sheet(title="Trends")
            
            trends_sheet.append(['PERFORMANCE TRENDS'])
            trends_sheet.merge_cells('A1:D1')
            trends_sheet['A1'].style = self.default_styles['title']
            
            row = 3
            for trend_name, trend_data in trends.items():
                if trend_data:
                    # Trend title
                    display_name = trend_name.replace('_', ' ').title()
                    trends_sheet.cell(row=row, column=1, value=display_name).style = self.default_styles['subheader']
                    row += 1
                    
                    # Headers
                    trends_sheet.append(['Period', 'Count', 'Amount'])
                    header_row = row
                    for col in range(1, 4):
                        trends_sheet.cell(row=header_row, column=col).style = self.default_styles['header']
                    row += 1
                    
                    # Data
                    for item in trend_data[:12]:  # Limit to 12 periods
                        period = item.get('month', item.get('period', ''))
                        if isinstance(period, str) and len(period) > 10:
                            period = period[:10]  # Truncate if too long
                        
                        trends_sheet.append([
                            period,
                            item.get('count', 0),
                            float(item.get('amount', 0)) if item.get('amount') else ''
                        ])
                        
                        # Apply styles
                        trends_sheet.cell(row=row, column=1).style = self.default_styles['normal']
                        trends_sheet.cell(row=row, column=2).style = self.default_styles['normal']
                        if item.get('amount'):
                            trends_sheet.cell(row=row, column=3).style = self.default_styles['amount']
                        row += 1
                    
                    row += 2  # Space between trends
            
            # Auto-adjust columns
            self._auto_adjust_columns(trends_sheet)
    
    def _create_metrics_sheets(self, report_data):
        """Create various metrics sheets."""
        # Loan metrics
        loan_metrics = report_data.get('loan_metrics', [])
        if loan_metrics:
            loan_metrics_sheet = self.workbook.create_sheet(title="Loan Metrics")
            self._create_metrics_table(loan_metrics_sheet, "LOAN METRICS", loan_metrics)
        
        # Payment metrics
        payment_metrics = report_data.get('payment_metrics', [])
        if payment_metrics:
            payment_metrics_sheet = self.workbook.create_sheet(title="Payment Metrics")
            self._create_metrics_table(payment_metrics_sheet, "PAYMENT METRICS", payment_metrics)
    
    def _create_metrics_table(self, sheet, title, metrics):
        """Create a metrics table in a sheet."""
        sheet.append([title])
        sheet.merge_cells('A1:G1')
        sheet['A1'].style = self.default_styles['title']
        
        if not metrics:
            return
        
        # Headers (using first item to determine columns)
        first_item = metrics[0]
        headers = list(first_item.keys())
        sheet.append(headers)
        
        header_row = sheet.max_row
        for col in range(1, len(headers) + 1):
            sheet.cell(row=header_row, column=col).style = self.default_styles['header']
        
        # Data
        for item in metrics:
            row = []
            for header in headers:
                value = item.get(header, '')
                
                # Format dates
                if 'date' in header.lower() or 'month' in header.lower():
                    if isinstance(value, str) and len(value) > 10:
                        value = value[:10]
                
                row.append(value)
            
            sheet.append(row)
        
        # Apply styles
        for row in range(header_row + 1, sheet.max_row + 1):
            for col in range(1, len(headers) + 1):
                cell = sheet.cell(row=row, column=col)
                value = cell.value
                
                if isinstance(value, (int, float)):
                    if col > 1:  # Assume first column is period
                        cell.style = self.default_styles['amount']
                else:
                    cell.style = self.default_styles['normal']
        
        # Auto-adjust columns
        self._auto_adjust_columns(sheet)
    
    def _create_metadata_sheet(self, metadata):
        """Create metadata sheet."""
        meta_sheet = self.workbook.create_sheet(title="Metadata")
        
        meta_sheet.append(['REPORT METADATA'])
        meta_sheet.merge_cells('A1:B1')
        meta_sheet['A1'].style = self.default_styles['title']
        
        row = 3
        for key, value in metadata.items():
            display_key = ' '.join(word.capitalize() for word in key.split('_'))
            meta_sheet.cell(row=row, column=1, value=display_key).style = self.default_styles['normal']
            meta_sheet.cell(row=row, column=2, value=str(value)).style = self.default_styles['normal']
            row += 1
        
        # Add system info
        row += 1
        meta_sheet.cell(row=row, column=1, value='System Information').style = self.default_styles['subheader']
        row += 1
        
        system_info = {
            'Generated by': 'Super Legit Advance Reporting System',
            'Version': '1.0.0',
            'Timestamp': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
        }
        
        for key, value in system_info.items():
            meta_sheet.cell(row=row, column=1, value=key).style = self.default_styles['normal']
            meta_sheet.cell(row=row, column=2, value=value).style = self.default_styles['normal']
            row += 1
        
        # Auto-adjust columns
        self._auto_adjust_columns(meta_sheet)
    
    def _create_export_summary(self, sheet, title, columns, data, generated_by):
        """Create export summary sheet."""
        sheet.append(['EXPORT SUMMARY'])
        sheet.merge_cells('A1:B1')
        sheet['A1'].style = self.default_styles['title']
        
        sheet.append(['Export:', title])
        sheet.append(['Generated by:', generated_by or 'System'])
        sheet.append(['Generated on:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')])
        sheet.append(['Total records:', len(data)])
        sheet.append(['Columns:', len(columns)])
        
        sheet.append([])  # Empty row
        
        # Column list
        sheet.append(['COLUMNS IN EXPORT'])
        sheet.merge_cells('A8:B8')
        sheet['A8'].style = self.default_styles['subheader']
        
        row = 9
        for i, column in enumerate(columns, 1):
            sheet.cell(row=row, column=1, value=f"{i}.").style = self.default_styles['normal']
            sheet.cell(row=row, column=2, value=column).style = self.default_styles['normal']
            row += 1
        
        # Auto-adjust columns
        self._auto_adjust_columns(sheet)
    
    def _auto_adjust_columns(self, sheet):
        """Auto-adjust column widths based on content."""
        for column in sheet.columns:
            max_length = 0
            column_letter = get_column_letter(column[0].column)
            
            for cell in column:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            
            adjusted_width = min(max_length + 2, 50)  # Cap at 50 characters
            sheet.column_dimensions[column_letter].width = adjusted_width
    
    def _create_pie_chart(self, sheet, title, label_col, data_col, start_row, end_row):
        """Create a pie chart in the sheet."""
        pie_chart = PieChart()
        pie_chart.title = title
        
        labels = Reference(sheet, min_col=ord(label_col) - 64, min_row=start_row, max_row=end_row)
        data = Reference(sheet, min_col=ord(data_col) - 64, min_row=start_row, max_row=end_row)
        
        pie_chart.add_data(data, titles_from_data=False)
        pie_chart.set_categories(labels)
        
        # Position chart
        sheet.add_chart(pie_chart, f"F{start_row}")
    
    def _create_bar_chart(self, sheet, title, label_col, data_col, start_row, end_row):
        """Create a bar chart in the sheet."""
        bar_chart = BarChart()
        bar_chart.title = title
        bar_chart.style = 10
        bar_chart.y_axis.title = 'Amount'
        bar_chart.x_axis.title = 'Method'
        
        labels = Reference(sheet, min_col=ord(label_col) - 64, min_row=start_row, max_row=end_row)
        data = Reference(sheet, min_col=ord(data_col) - 64, min_row=start_row, max_row=end_row)
        
        bar_chart.add_data(data, titles_from_data=False)
        bar_chart.set_categories(labels)
        
        # Position chart
        sheet.add_chart(bar_chart, f"F{start_row}")