# Generated by Django 4.2.27 on 2026-01-21 20:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('penalty_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Penalty Number')),
                ('penalty_type', models.CharField(choices=[('LATE_PAYMENT', 'Late Payment'), ('DEFAULT', 'Default'), ('EARLY_REPAYMENT', 'Early Repayment'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='LATE_PAYMENT', max_length=20, verbose_name='Penalty Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Penalty Amount (KES)')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='Status')),
                ('calculation_method', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('DAILY_RATE', 'Daily Rate'), ('FLAT_FEE', 'Flat Fee')], default='PERCENTAGE', max_length=50, verbose_name='Calculation Method')),
                ('calculation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Calculation Rate (%)')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='Days Overdue')),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base Amount (KES)')),
                ('applied_date', models.DateField(default=django.utils.timezone.now, verbose_name='Applied Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Paid (KES)')),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Outstanding (KES)')),
                ('waiver_reason', models.TextField(blank=True, verbose_name='Waiver Reason')),
                ('waiver_date', models.DateField(blank=True, null=True, verbose_name='Waiver Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('repayment_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Repayment Number')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Due (KES)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Paid (KES)')),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Outstanding (KES)')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Principal Amount (KES)')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Interest Amount (KES)')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Penalty Amount (KES)')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Fee Amount (KES)')),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='MPESA', max_length=20, verbose_name='Payment Method')),
                ('repayment_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('INTEREST', 'Interest'), ('PENALTY', 'Penalty'), ('FEE', 'Fee'), ('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment')], default='FULL', max_length=20, verbose_name='Repayment Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial'), ('WAIVED', 'Waived')], default='PENDING', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='Days Overdue')),
                ('late_fee_applied', models.BooleanField(default=False, verbose_name='Late Fee Applied')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Receipt Number')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='repayment_receipts/%Y/%m/%d/', verbose_name='Receipt File')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
            ],
            options={
                'verbose_name': 'Repayment',
                'verbose_name_plural': 'Repayments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('installment_number', models.IntegerField(verbose_name='Installment Number')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Principal Amount (KES)')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Amount (KES)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount (KES)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped'), ('ADJUSTED', 'Adjusted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Paid (KES)')),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Outstanding (KES)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='Days Overdue')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Late Fee (KES)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_adjusted', models.BooleanField(default=False, verbose_name='Adjusted')),
                ('adjustment_reason', models.TextField(blank=True, verbose_name='Adjustment Reason')),
                ('original_due_date', models.DateField(blank=True, null=True, verbose_name='Original Due Date')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Original Amount (KES)')),
            ],
            options={
                'verbose_name': 'Repayment Schedule',
                'verbose_name_plural': 'Repayment Schedules',
                'ordering': ['loan', 'installment_number'],
            },
        ),
    ]
