# Generated by Django 4.2.27 on 2026-01-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repayments', '0001_initial'),
        ('customers', '0002_initial'),
        ('loans', '0002_initial'),
        ('mpesa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repaymentschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loans.loan', verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='repayments.repayment', verbose_name='Repayment'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_repayments', to=settings.AUTH_USER_MODEL, verbose_name='Collected By'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan', verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='mpesa_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='mpesa.mpesapayment', verbose_name='M-Pesa Payment'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_repayments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Applied By'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='loans.loan', verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='repayments.repayment', verbose_name='Repayment'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Waived By'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['loan', 'due_date'], name='repayments__loan_id_a49ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['status'], name='repayments__status_d72326_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['due_date'], name='repayments__due_dat_a6b803_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['customer', 'status'], name='repayments__custome_83251f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repaymentschedule',
            unique_together={('loan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['repayment_number'], name='repayments__repayme_91518a_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='repayments__status_8bb44a_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['due_date'], name='repayments__due_dat_f464ba_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['payment_date'], name='repayments__payment_6ec733_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['loan', 'status'], name='repayments__loan_id_b2eb57_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['customer', 'status'], name='repayments__custome_0a8f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['penalty_number'], name='repayments__penalty_97691d_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['status'], name='repayments__status_eeebe7_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['applied_date'], name='repayments__applied_ccb799_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['loan', 'status'], name='repayments__loan_id_67ec4b_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['customer', 'status'], name='repayments__custome_6c8ccc_idx'),
        ),
    ]
